### ISSUE TITLE
Proceso para versionar elementos de configuración error ortográfico

### ISSUE THREAD

**Issue by ianroses** [CaveLabs-1/Wiki#184]
En la definición de fases, fase 3. Dice "Los resultados de las auditrias [...]" cuando debe ser "Los resultados de las auditorias [...]".
En la parte de Métricas utilizadas, Dice "Número de dias" cuando debe ser "Número de días"
Y en la bitácora en la versión 1 "Mauricio Hernandez"  a "Mauricio Hernández"

**Comment by pirty6** [comment]
se corrigió en la versión 2.0
