### ISSUE TITLE
Error ortográfico en guía de herramientas

### ISSUE THREAD

**Issue by ianroses** [CaveLabs-1/Wiki#187]
Aparece "Si consideras que hay una mejor versión, hablalo con el departamento para que lleguen a un acuerdo y de ésta manera todos sepan que version necesitan tener." cuando debe de ser "Si consideras que hay una mejor versión, háblalo con el departamento para que lleguen a un acuerdo y de esta manera todos sepan que versión necesitan tener."

**Comment by pirty6** [comment]
checa el pull-request
